name: rewatch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  carousel_slider: ^5.1.1
  palette_generator: ^0.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  flutter_inset_box_shadow_update: ^0.0.1
  animated_toggle_switch: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
